### ISSUE TITLE
Same cluster issue for large number of records

### ISSUE THREAD

**Issue by BalasahebHimanshu** [pierredavidbelanger/ekmeans#5]
Hi,

We have used this code to cluster the records. It is working fine but when we import large number of records then it taking too much of time. How can we improve the performance. We have used 50K records. 

Note: We also convert all code into C# still it taking too much of time. It is taking time in makeAssignment() function.

Please anyone help me to resolve this performance issue.

Thanks!

**Comment by pierredavidbelanger** [comment]
Hi @BalasahebHimanshu , 

if you do not use the `eKmeans.setEqual(true);` option, the kmeans algo should be fairly fast even with 50k data point.

**Comment by BalasahebHimanshu** [comment]
Hi,

Thanks for your reply. 

Can you please let us know what is the purpose of **eKmeans.setEqual(true)**; this line of code and when we do not use **eKmeans.setEqual(true)**; this then it impact anything for cluster making.

Thanks!
Balasaheb

**Comment by pierredavidbelanger** [comment]
from the [About section](/pierredavidbelanger/ekmeans/blob/master/README.md#about)

> A Java K-means Clustering implementation with an optional special equal option that **apply an equal cardinality constraint on the clusters** while remaining as spatially cohesive as possible.

In other words: the `equal` option, tries to create clusters of the same size. You should not use this option if you do not need this, because it can sometime produce clusters that are not as spatially cohesive as the original K-means algorithm.

**Comment by BalasahebHimanshu** [comment]
Hi,

Thanks for your reply. Yes we got it but we want to create clusters with same size. Is there any solution to increase performance.

Thanks!
Balasaheb

**Comment by pierredavidbelanger** [comment]
> Is there any solution to increase performance.

With kmeans, not that I can think of, no.

I can suggest you to have a look at an [implementation of an agglomerative hierarchical clustering algorithm in Java](https://github.com/lbehnke/hierarchical-clustering-java). It will be a little harder to have equal cardinality clusters, but you will definitely be able to gain performance.
